services:
  - name: email-validation-api
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
