services:
  - name: email-verifier
    type: web
    runtime: python
    envVars:
      - key: PORT
        value: 10000
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --bind 0.0.0.0:$PORT
    autoDeploy: true
